# SITE CONFIGURATION
baseurl: "https://www.firststratum.com"
url: "https://www.firststratum.com"
title: First Stratum # site's title
description: "Blogs for Networkers" # used by search engines


# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: First Stratum # blog's title
  avatar: assets/img/triangle.svg
  favicon: assets/favicon.ico
  gravatar: # Email MD5 hash

  # Header and footer text
     # <p> <font color="black"> <This is a website designed by Raymond Shiner for Networker Maxwell Wenger under codename First Stratum.</font> <img align="top"> <br/> </p>
  header_text: > #two or three lines to describe your site
   <b>Software Engineering, Networking, and Consulting at its finest.</b>
  header_text_feature_image: assets/img/pexels/hallway.png
  footer_text: >
   Designed, Built, and Maintained by Raymond Shiner - Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a>

  # Icons
  rss: true  # Make sure you created a feed.xml with feed.xml layout
  email_address: "max@maxwellwenger.com" # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook: true
  flickr:
  gitlab:
  github: "mwenger"
  google_plus:
  instagram:
  keybase:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam: 
  tumblr:
  twitter: # "twitter username"
  vimeo:
  wordpress:
  youtube:
  
  # Sharing options
  share_buttons:
    facebook: true
    twitter: true
    google_plus: 
    tumblr:
    pinterest:
    pocket:
    reddit: true
    linkedin:
    wordpress:
    email: true

  # Scripts / Features 
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup
  
  special_page:
    search: 
      icon: "search" # Assuming page link and icon are the same
      enabled: true
    tags:
      icon: "tags"
      enabled: true
  
  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_share_on: "Share on"
  str_add_to: "Add to"
  str_email: "Email"
  str_tweet: "Tweet"
  str_pin_it: "Pin it"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true
  
  
# PAGINATION
paginate: 5
paginate_path: "blog/page:num"


# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name


# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag]
#theme: type-on-strap # Uncomment if using the theme as a jekyll theme gem
exclude: ["Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", "LICENSE", "README.md", "screenshot.png", "package.json", "node_modules", "gulpfile.js", ".idea/*"]


#Custom Build Settings
defaults:
  -
    scope:
      path: "pages"
    values:
      layout: "page"
